name: customizable_multiselect_field
description: A Flutter package that provides a highly customizable multiselect field.
version: 1.0.0
repository: https://github.com/thoffart/customizable_multiselect_field
homepage: https://github.com/thoffart/customizable_multiselect_field

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
